### ISSUE TITLE
C# application implementation storyline game

### ISSUE THREAD

**Issue by pedor** [thomasroose/ProjectLab-2#15]

**Comment by pedor** [comment]
Verhaal(temporary)

[story(base idea).txt](https://github.com/thomasroose/ProjectLab-2/files/932893/story.base.idea.txt)
![blind date](https://cloud.githubusercontent.com/assets/11293707/25172183/7ef25a2c-24f0-11e7-94fb-f2d5048e2079.jpg)
![prof](https://cloud.githubusercontent.com/assets/11293707/25172184/7efb2260-24f0-11e7-8ca4-03eef0821a9d.png)

**Comment by thomasroose** [comment]
Verhaal is geïmplementeerd
