### ISSUE TITLE
Visible light protocol

### ISSUE THREAD

**Issue by thomasroose** [thomasroose/ProjectLab-2#2]
Which visible light protocol do we use?

**Comment by thomasroose** [comment]
Which visible light protocol do we use?

**Comment by pedor** [comment]
Gekeken voor Forward Error Correction (FEC) voor ons project,uitgekomen op Hamming code.
Deze code wordt gebruikt om 1 bit fouten te corrigeren zonder hierbij nood te hebben aan een retransmissie.
Een nadeel is wel dat er extra bits meegestuurd worden wat de uiteindelijke boodschap langer maakt maar in ons project zou dit niet voor problemen moeten zorgen.
Online gezocht achter een code-voorbeeld hiervoor,uitgekomen op code voor de Hammming(7.4) (7 bits lang,4 data bits,3 pariteitbits),deze aangepast zodat we met de Hamming(15,11) (15 bits lang,11 databits,4 pariteitbits) kunnen werken.
De code op zich vraagt wel nog steeds om manueel de boodschap en ontvangen data in te geven,maar dit aanpassen zodat dit automatisch gebeurt in onze mbeds zou geen probleem moeten zijn.

Na mekaar ontmoet te hebben  op 19/04 ondervonden dat 11 bits nog steeds te weinig plaats is,vandaar de code aangepast naar Hamming(21,16)

Een link voor een video waarbij ze het concept uitleggen (met een leuk deuntje):
https://www.youtube.com/watch?v=373FUw-2U2k
[HammingCode(7,4).txt](https://github.com/thomasroose/ProjectLab-2/files/923946/HammingCode.7.4.txt)
[HammingCode(15,11).txt](https://github.com/thomasroose/ProjectLab-2/files/923947/HammingCode.15.11.txt)
[HammingCode(21,16).txt](https://github.com/thomasroose/ProjectLab-2/files/949982/HammingCode.21.16.txt)

**Comment by pedor** [comment]
Hamming code aangepast zodat we uiteindelijk 16 databits hebben en 5 pariteitbits.
Naast Hamming code maken we ook gebruik van Manchester encodering,dit om synchronisatie mogelijk te maken.
