### ISSUE TITLE
Mbed (1-4) implementation

### ISSUE THREAD

**Issue by thomasroose** [thomasroose/ProjectLab-2#4]

**Comment by pedor** [comment]
[MBED(1-4)_noman.txt](https://github.com/thomasroose/ProjectLab-2/files/956732/MBED.1-4._noman.txt)
[RGB.txt](https://github.com/thomasroose/ProjectLab-2/files/958374/RGB.txt)
[RGB(header).txt](https://github.com/thomasroose/ProjectLab-2/files/958378/RGB.header.txt)

Voorlopige versie,4 kleuren,16databits,verwerkt door de hammingcode tot een 21bit boodschap,op 26/04 zal ik deze uittesten

**Comment by pedor** [comment]
[MBED(1-4)_noman_100%demping.txt](https://github.com/thomasroose/ProjectLab-2/files/958357/MBED.1-4._noman_100.demping.txt)
Versie die getest is geweest,100% demping (led volledig aan/uit),nog geen Manchesterencoding geïmplementeerd.

**Comment by pedor** [comment]
[ManchesterMBED.txt](https://github.com/thomasroose/ProjectLab-2/files/966848/ManchesterMBED.txt)
Versie met Manchesterencoding geïmplementeerd.
