### ISSUE TITLE
Properties visible light communication

### ISSUE THREAD

**Issue by thomasroose** [thomasroose/ProjectLab-2#5]
Simplex?
Biterrors?
Synchronisation?
Overhead?

**Comment by pedor** [comment]
-Simplex daar we enkel een sensor hebben op de handheld. 
-Biterrors worden gecorrigeerd door de hamming-code
-Synchronisation is mogelijk m.b.v. Manchester-codering,welke nog ontworpen en getest moet worden
-Overhead wordt beïnvloed door de hamming-code,de andere factoren onderzoeken eens we een werkend circuit hebben.
